### ISSUE TITLE
Button background and border preview conflict in customizer

### ISSUE THREAD

**Issue by aryanrajseo** [seothemes/genesis-customizer-theme#2] opened 2019-04-01 15:00 UTC
Base Styles > Buttons. Selecting border color at first, then adding border width not show any changes. User need to go back and select the color border.  

Re-adding border color value makes gradients color away and when you change background gradients, border go away.

**Comment by seothemes** [comment] 2019-04-03 03:23
Duplicate of #4

**Closed as completed by seothemes** 2019-04-03 03:23 UTC
Labels: duplicate
